version: "3.8"

services:
  mysqlDb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: kaddem
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql

  app-kaddem:
    depends_on:
      - mysqlDb
    image: medhioub12/kaddem-devops:1.0.0
    restart: on-failure
    ports:
      - "8082:8089"
    environment:
      SPRING_APPLICATION_JSON: '
        {
          "spring.datasource.url": "jdbc:mysql://mysqlDb:3306/kaddem?createDatabaseIfNotExist=true",
          "spring.datasource.username": "root",
          "spring.datasource.password": "",
          "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect",
          "spring.jpa.hibernate.ddl-auto": "update"
        }'
    stdin_open: true
    tty: true

volumes:
  db:
