services:
  mysqldb:
    image: mysql # Replace with your MySQL image
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: kaddem
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    ports:
      - "3307:3306"  # Expose MySQL port
    volumes:
      - db:/var/lib/mysql
  app-kaddem:
    image: skandernasri1/devopsproject:1.0.0  # Replace with your Alpine app image
    depends_on:
      - mysqldb  # Ensure MySQL is started before the app
    restart: on-failure
    ports:
      - "8082:8082"  # Expose your app port
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mysql://mysqldb:3306/kaddem/db?&createDatabaseIfNotExist=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5Dialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    stdin_open: true
    tty: true
volumes:
  db: